### ISSUE TITLE
For Thursday, June 23rd

### ISSUE THREAD

**Issue by mnatenz1** [Upward-Spiral-Science/orange-panda#1]
**by thurs** 
- [x] 1. More Research on What Can Be Done with BCI (Everyone reads and puts forward at least 3 papers/resources). 
Success: Upload summaries of papers (1-2 paragraph). In addition, what does the paper show about what possibilities are available in BCI/what applications and limitations are in BCI? Does the paper provide usable datasets? These last 2 questions should also be 1-2 paragraphs.

- [x] 2. Narrow Down Topic of Focus, Choose Problem. To represent the problem, we will update only part 1 of the proposal document (i.e. just replacing the Problem Statement portion of it) 
Success: New Problem Statement, based on the information found in 1

**by mon**
- [ ] 3. Find Relevant Data / Research online (5 per person). More focused search than part 1. These papers are oriented on the problem from part 2 or are datasets with relevant information to new problem. 
Success: Summary of paper/data (1-2 paragraphs) and description of applicability to project (1 paragraph). If available, what data is provided (1 paragraph)

- [ ] 4. Rewrite Proposal
Success: Rewrite proposal based on parts 2 and 3.

**Tentative Action Plan**

- [x]  Tuesday: Noon - Atrium
(est. 1)

- [x]  Wednesday: Noon - Atrium
(est. 1 + 2)

- [x]  Thursday: 1:00PM- Atrium
(est. 2 + 3 +(4?))

**Comment by nkumarcc** [comment]
We were unable to come to a decision on Thursday for narrowing down the topic. After discussing our research and debating the direction to go, we decided to spend one more day to mull over potential ways of defining a problem, and to force ourselves to move forwards tomorrow.

**Comment by jovo** [comment]
:ok_hand:

On Thu, Jun 23, 2016 at 2:17 PM, nkumarcc <notifications@github.com> wrote:

> We were unable to come to a decision on Thursday for narrowing down the
> topic. After discussing our research and debating the direction to go, we
> decided to spend one more day to mull over potential ways of defining a
> problem, and to force ourselves to move forwards tomorrow.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Upward-Spiral-Science/orange-panda/issues/1#issuecomment-228137103>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AACjclLRYblBTEVZv5bfAiGVJ1Oh_EAlks5qOs2mgaJpZM4I6J3O>
> .
>



-- 
the glass is all full:  half water, half air.
neurodata.io, jovo calendar
<https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>

**Comment by nkumarcc** [comment]
Modified goals one more time. First, we had done research into potential of BCi and background and shared it, but still were having trouble coming to a consensus, and we feel like it may have been due to lack of potential problems to discuss, just general boundaries of BCI. Spending next day looking at potential PROBLEMS and seeing if there is a BCI application available.

**Comment by jovo** [comment]
ok goals shouldn't be editted midweek, rather, feedback provided to enable us to generate refined goals for next week.

**Comment by nkumarcc** [comment]
Sounds good, changed it back, and we'll think about the trouble we had when choosing new goals.
