### ISSUE TITLE
For September 12th

### ISSUE THREAD

**Issue by nkumarcc** [Upward-Spiral-Science/orange-panda#11]
@tsunwong123:
- [x] Heatmaps of timeseries data (rows electrodes / col timesteps) - [.Rmd explaining code](https://github.com/Upward-Spiral-Science/orange-panda/blob/master/eeg_data/EEG_Plots/9_12/HeatMaps/09_12_2016.Rmd) + [screenshots of plot](https://github.com/Upward-Spiral-Science/orange-panda/tree/master/eeg_data/EEG_Plots/9_12/HeatMaps)
    - [x] 6 panels, which stands for the 6 paradigms, [each downsample of time](https://github.com/Upward-Spiral-Science/orange-panda/tree/master/eeg_data/EEG_Plots/9_12/HeatMaps)
- [x] Time Domain - [.Rmd explaining code](https://github.com/Upward-Spiral-Science/orange-panda/blob/master/eeg_data/EEG_Plots/9_12/RandomChunks/09_12_2016_eeg.Rmd) + [screenshots of plot](https://github.com/Upward-Spiral-Science/orange-panda/tree/master/eeg_data/EEG_Plots/9_12/RandomChunks)
    - [x] look at random chunks of 

@nkumarcc:
- [x] Fix electrode row naming - [pic of fix in code](https://github.com/Upward-Spiral-Science/orange-panda/blob/master/eeg_data/EEG_Plots/code_pics/eeg_labels.png)
- [x] Frequency Domain - .Rmd explaining fixes done + [screenshots](https://github.com/Upward-Spiral-Science/orange-panda/blob/master/eeg_data/EEG_Plots/freq_plots/A00051826_rest_Cz.png)
    - [ ] 6 panels power over entire trial, Time col = trials per subject
- [x] Make pupil location eyetracking plots - .Rmd explaining fixes done + [screenshots](https://github.com/Upward-Spiral-Science/orange-panda/tree/master/eeg_data/eye_plots/pupil_locations)
- [x] Remove half of the subjects and half of the data- .md of which patients we'll use

@mike:
- [x] Read 80 more pages of book - [.doc of notes](http://upward-spiral-science.github.io/orange-panda/AnalyzingNeuralTimeSeriesData_Week02.pdf) + [summary](https://github.com/Upward-Spiral-Science/orange-panda/blob/gh-pages/09_12_2016_summary_p160.md)

@rmarren1:
- [x] Read data sharing paper - [.md](https://github.com/Upward-Spiral-Science/orange-panda/blob/master/brainstorm/Data_Sharing_Paper_Notes_Marren.md) of possible data patterns which might intuitively correspond with some symptoms of disorders / questions 
- [x] Read through BCI textbook notes [slideshow 1](http://upward-spiral-science.github.io/orange-panda/reveal/week1.html#/) & [slideshow 2](http://upward-spiral-science.github.io/orange-panda/reveal/week2.html#/) - [.md](https://github.com/Upward-Spiral-Science/orange-panda/blob/master/brainstorm/BCI_Text_Notes.md) of points relevant to the current project we may have forgotten
- [x] Download data and metadata from one subject - screenshots of opening and looking through it
  - [eeg](https://www.dropbox.com/s/uliolhnimsl404o/Selection_003.png?raw=1)
  - [blink](https://www.dropbox.com/s/tnqohqyu2c0116j/Selection_004.png?raw=1)
  - [fixation](https://www.dropbox.com/s/ksq4yban4oxwb74/Selection_005.png?raw=1)
  - [saccade](https://www.dropbox.com/s/mlqfmv0i74jz2cm/Selection_006.png?raw=1)
  - [userevent](https://www.dropbox.com/s/6627vf4gf1yy4c1/Selection_007.png?raw=1)

- [Organized data pipeline notes from the meeting on friday morning](https://docs.google.com/document/d/1mR3pLZWoKc5MLTeyEKzi6QSS2G-OZK_2Xd_lkQagSfA/edit#)

**Comment by gkiar** [comment]
👌

**Comment by rmarren1** [comment]
@gkiar updated with my tasks after I was able to speak more with team

**Comment by gkiar** [comment]
👌 great, thanks!

**Comment by gkiar** [comment]
Great work 😄
