### ISSUE TITLE
For Tuesday, July 5th

### ISSUE THREAD

**Issue by nkumarcc** [Upward-Spiral-Science/orange-panda#2]
- [x]  Mike: Research at least 10 different wearables/smart phones and the sensors they contain (and biomarkers they measure), as well as the efficacy of the sensors. Represent these findings in a table for everyone to refer to.

- [x]  Tsun: Substance Abuse Nitin: PTSD. Each person looks up:
1. Papers describing influence of biomarkers on area
2. Datasets of biomarkers tested in the area
3. Papers describing BCI related treatment of the disease
4. Datasets of BCI related treatments.

Find 6 of each, present links in one file. Each link gets 2-3 sentences describing what data/discovery is in information. Also, if data is from Hopkins, state that is and from who.

- [x]  Chapters 10,11 from textbook

**Comment by jovo** [comment]
recall *feasibility* has to do with us, in particular, are *we* the best
team to do this?
or, might some other team already have a huge head start, more resources,
more knowledge, etc.
remember, to have impact in a competitive market, we can't just have an
idea,
we need a better idea :)

On Mon, Jun 27, 2016 at 4:03 PM, nkumarcc <notifications@github.com> wrote:

>
>    -
>
>    Mike: Research at least 10 different wearables/smart phones and the
>    sensors they contain (and biomarkers they measure), as well as the efficacy
>    of the sensors. Represent these findings in a table for everyone to refer
>    to.
>    -
>
>    Tsun: Substance Abuse Nitin: PTSD. Each person looks up:
>
>
>    1. Papers describing influence of biomarkers on area
>    2. Datasets of biomarkers tested in the area
>    3. Papers describing BCI related treatment of the disease
>    4. Datasets of BCI related treatments.
>
> Find 6 of each, present links in one file. Each link gets 2-3 sentences
> describing what data/discovery is in information. Also, if data is from
> Hopkins, state that is and from who.
>
>    - Chapters 10,11 from textbook
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Upward-Spiral-Science/orange-panda/issues/2>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AACjcjmiE0Jtwb7nPVZrbjeUmu6opESJks5qQCx8gaJpZM4I_dAS>
> .
>



-- 
the glass is all full:  half water, half air.
neurodata.io, jovo calendar
<https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>
