### ISSUE TITLE
reconsider EEG data

### ISSUE THREAD

**Issue by jovo** [Upward-Spiral-Science/orange-panda#3]
- [x] [read last 2 chapters of book](http://upward-spiral-science.github.io/orange-panda/reveal/week6.html)
- [x] read EEG paper @jovo sent carefully, summarize in slides, link to slide [here](http://upward-spiral-science.github.io/orange-panda/eeg_analysis/Medical_EEG_Data_Descriptors.html):
- [x] read EEG analysis paper, potentially one that @jovo finds, summarize in slides, link to slide here: [slides!](http://upward-spiral-science.github.io/orange-panda/eeg_analysis/topographic_epr_analysis.html#/)
- [x] read naturalistic paradigm papers, and make notes in the repo as an md file here:
- [Audience preferences are predicted by temporal reliability of neural processing](http://upward-spiral-science.github.io/orange-panda/eeg_analysis/Temporal_Reliability_Neural_Processing.html) - [Link to Artcle](http://www.ncbi.nlm.nih.gov/pubmed/25072833)
- [EEG as Possible Marker for Engagement](http://upward-spiral-science.github.io/orange-panda/eeg_analysis/Marker_For_Engagement.html#/) - [Link to Article](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3353265/)
- [x] update "design docs", eg, answer to questions, link to updated md file [here](https://github.com/Upward-Spiral-Science/orange-panda/blob/master/proposal.md): 
- [ ] find EEG analysis python code, summarize in slides here:
- [ ] do course 1 & 2 of https://www.coursera.org/specializations/jhu-data-science

**Comment by mnatenz1** [comment]
- Did not have time to look for EEG analysis python code
- Could not gain access to coursera files for free (did not realize there was another means of attaining the files without having to pay)
