### ISSUE TITLE
For Monday July 25th

### ISSUE THREAD

**Issue by nkumarcc** [Upward-Spiral-Science/orange-panda#5]
- [ ] Research the stages of EEG analysis (preprocessing, source localization, etc.). Create an md  file with them here to discuss by Friday: 
    - [ ] Create slides about them and discuss as a group. Slides of stages here:
- [x] Finish course 2 of [Coursera](https://www.coursera.org/specializations/jhu-data-science)
- [x] Finish course 3 of [Coursera](https://www.coursera.org/specializations/jhu-data-science)

**Comment by mnatenz1** [comment]
Did some background research for bullet one but never compiled into a file.
