### ISSUE TITLE
August 22nd, 2016

### ISSUE THREAD

**Issue by jovo** [Upward-Spiral-Science/orange-panda#8]
- [ ] Coursera (Course 6 - Weeks 3/4) + Course 7
    - [ ] Nitin Course 6 and Course 7 
    - [x] Mike [Course 6](https://github.com/Upward-Spiral-Science/orange-panda/blob/master/coursera/course-6-statistical/statistical-inference-2-mike.pdf) and [Course 7 ](https://github.com/Upward-Spiral-Science/orange-panda/blob/master/coursera/course-7-regression/regression-model-mike.pdf)
    - [ ] Tsun Course 6 and Course 7 
- [x] Nitin: Direct access to Amazon S3. Markdown with code. [Just the code.](https://github.com/Upward-Spiral-Science/orange-panda/blob/master/eeg_data/access_amazon.R)
- [x] Mike: Read in Eye Sample Data. R markdown to represent its capability.
- [x] Mike/Tsun: Make at least 5 eye tracking plots. Markdown with [plots](https://github.com/Upward-Spiral-Science/orange-panda/tree/master/EyeTracking_Plots) + [code](https://github.com/Upward-Spiral-Science/orange-panda/blob/master/eeg_data/eyetrack_event_plots.R) + [short description](https://github.com/Upward-Spiral-Science/orange-panda/blob/master/eeg_data/eyetrack_description.md).
- [x] Nitin: Read in EEG Data. R markdown to represent its capability. [Just the code](https://github.com/Upward-Spiral-Science/orange-panda/blob/master/eeg_data/eeg_read.R)
- [ ] Nitin/Tsun: Make at least 5 EEG Plots. Markdown with [plots](https://github.com/Upward-Spiral-Science/orange-panda/tree/master/eeg_data/EEG_Plots) + code + short description.

**Comment by mnatenz1** [comment]
[Presentation](http://upward-spiral-science.github.io/orange-panda/Week_08_22_16.html)

**Comment by nkumarcc** [comment]
We didn't complete Coursera because of the unexpected amount of time trying to effectively complete the data goals. The EEG plots were also hindered because of difficulty reading in the data, but we tried making some relevant plots eventually (didn't meet goal though).
