### ISSUE TITLE
For August 29th

### ISSUE THREAD

**Issue by nkumarcc** [Upward-Spiral-Science/orange-panda#9]
- [ ] Nitin/Tsun Coursera 6 (weeks 3 +4) and Course 7
    - [ ] Nitin notes- ch6.pdf + ch7.pdf
    - [x] Tsun notes- [ch6.doc](https://github.com/Upward-Spiral-Science/orange-panda/tree/master/coursera/course-6-statistical/tsun) 
- [x] Nitin [delete Git history with Amazon credentials](https://github.com/Upward-Spiral-Science/orange-panda/commits/master/eeg_data/access_amazon.R)
- [x] Nitin Integrate Amazon accessor into [readdata functions Rmd](https://github.com/Upward-Spiral-Science/orange-panda/blob/master/eeg_data/readdata/readdata.Rmd) Also included, [HTML upload](http://upward-spiral-science.github.io/orange-panda/readdata.html)
- [ ] Mike change "readfile" function to readeventfile, etc, clean up plot file- Rmd for both
- [x] Mike Update the [Eye Tracking Plots](https://github.com/Upward-Spiral-Science/orange-panda/tree/master/EyeTracking_Plots/8_29_Revision) (axes, both eyes on one plot, different colors). Put in rmd
- [x] Mike/Tsun [complete some research](http://upward-spiral-science.github.io/orange-panda/eeg_analysis/EEG_Filtering_Methods.html#/) on the analyses/plots that can be made with EEG
- [x] All : Use the research Mike compiles to create [different graphs of the EEG data](https://github.com/Upward-Spiral-Science/orange-panda/tree/master/eeg_data/EEG_Plots/8_29)

**Comment by jovo** [comment]
👌

**Comment by tsunwong123** [comment]
Nitin didn't finish coursera but will catch up next week
Mike didn't change the "readfile" function because there is no point- Nitin made more general functions instead but still need to be implemented
